#ifndef _ARM_ARMV7_PAGE_TABLE_H_
#define _ARM_ARMV7_PAGE_TABLE_H_

/* 页表大小 */
#define PAGE_TABLE_ENTRIES 4096
#define PAGE_TABLE_ENTRY_WIDTH 4
#define PAGE_TABLE_SIZE (PAGE_TABLE_ENTRIES * PAGE_TABLE_ENTRY_WIDTH)

#endif