#ifndef _TRUSTZONE_COMMUNICATION_CONSTANTS_H_
#define _TRUSTZONE_COMMUNICATION_CONSTANTS_H_

#define SMC_NS_ARG_TZ_API           (0x80000001)

#define TEEC_SUCCESS                (0x00000000)
#define TEEC_ERROR_GENERIC          (0xFFFF0000)
#define TEEC_ERROR_ACCESS_DENIED    (0xFFFF0001)
#define TEEC_ERROR_CANCEL           (0xFFFF0002)
#define TEEC_ERROR_ACCESS_CONFLICT  (0xFFFF0003)
#define TEEC_ERROR_EXCESS_DATA      (0xFFFF0004)
#define TEEC_ERROR_BAD_FORMAT       (0xFFFF0005)
#define TEEC_ERROR_BAD_PARAMETERS   (0xFFFF0006)
#define TEEC_ERROR_BAD_STATE        (0xFFFF0007)
#define TEEC_ERROR_ITEM_NOT_FOUND   (0xFFFF0008)
#define TEEC_ERROR_NOT_IMPLEMENTED  (0xFFFF0009)
#define TEEC_ERROR_NOT_SUPPORTED    (0xFFFF000A)
#define TEEC_ERROR_NO_DATA          (0xFFFF000B)
#define TEEC_ERROR_OUT_OF_MEMORY    (0xFFFF000C)
#define TEEC_ERROR_BUSY             (0xFFFF000D)
#define TEEC_ERROR_COMMUNICATION    (0xFFFF000E)
#define TEEC_ERROR_SECURITY         (0xFFFF000F)
#define TEEC_ERROR_SHORT_BUFFER     (0xFFFF0010)
#define TEEC_ERROR_TARGET_DEAD      (0xFFFF3024)

#endif